### ISSUE TITLE
Impossible to login with SSH

### ISSUE THREAD

**Issue by AlexanderShniperson** [coreos/coreos-cloudinit#302] opened 2015-01-22 06:56 UTC
Hello.
I wrote my cloud-config that set SSH port and keys for users, but i cant login with SSH key anyway, 
the server prompts me enter some password.

what went wrong?

here is my config file:
```
#cloud-config

hostname: CoreOS01

users:
  - name: core
    # Password: password
    passwd: $6$Z7TyN/ZtOHm/O$6JYggxF6fxh3epWjItfdQLJNzjoCAOdXUsfOyQ1QflAEIimY5ZeyB2Ha2YW.TCztz.1BtPHYujiH4Js4tXES.1
  - name: camka
    # Password: password
    passwd: $6$Z7TyN/ZtOHm/O$6JYggxF6fxh3epWjItfdQLJNzjoCAOdXUsfOyQ1QflAEIimY5ZeyB2Ha2YW.TCztz.1BtPHYujiH4Js4tXES.1
    groups:
      - sudo
      - docker
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCai45XB6SDrfRspSZTtkJoPsmBecIoLOveMpDJf5n25x/yo4ZH0EzlGZrCZkJfA8rqgiXGmp6kaaQ7rgN+E1KN43lkSKByrzfCrnfNAhgQrIsYYk2GdL1YxV9PL2zaCLu/uT+6/2gQIHyZ7RM5tQLVw1f7Kcug0LZafU7HN3LpPk13AtsmTqfphxXk/AfYSuTq2qqjOwZyjx3tj6D5pme8CmZySmcGUXJN423A3AsvVY6oIb/GuOldSkwp7XZKhta6M72R0pogmWeKPDZd5JYNx6IZLebHfII3/j5iVPBJwhnVo1VG39gHUjZOUbR+Lg8FcKTGB2tWLbWaowXT6TYB camkadev@Mac-mini-Aleksandr.local

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCai45XB6SDrfRspSZTtkJoPsmBecIoLOveMpDJf5n25x/yo4ZH0EzlGZrCZkJfA8rqgiXGmp6kaaQ7rgN+E1KN43lkSKByrzfCrnfNAhgQrIsYYk2GdL1YxV9PL2zaCLu/uT+6/2gQIHyZ7RM5tQLVw1f7Kcug0LZafU7HN3LpPk13AtsmTqfphxXk/AfYSuTq2qqjOwZyjx3tj6D5pme8CmZySmcGUXJN423A3AsvVY6oIb/GuOldSkwp7XZKhta6M72R0pogmWeKPDZd5JYNx6IZLebHfII3/j5iVPBJwhnVo1VG39gHUjZOUbR+Lg8FcKTGB2tWLbWaowXT6TYB camkadev@Mac-mini-Aleksandr.local

write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp
      PermitRootLogin no
      AllowUsers core camka
      PasswordAuthentication no
      ChallengeResponseAuthentication no

coreos:
  etcd:
      name: coreosnode001
      discovery: https://discovery.etcd.io/6a991fe781b0dc9ce27457879bfb7ab1
  units:
    - name: sshd.socket
      command: restart
      content: |
        [Socket]
        ListenStream=2211
        Accept=yes
```

**Comment by AlexanderShniperson** [comment] 2015-01-22 07:38
SSH server listening port doe not change to 2211 anyway

**Comment by crawford** [comment] 2015-01-22 19:03
I just tried your config on EC2 and it worked fine. What provider are you using?

**Comment by AlexanderShniperson** [comment] 2015-01-23 05:05
i am run at VirtualBox 4.3.20, maybe it is problem?

**Comment by crawford** [comment] 2015-01-23 17:39
Does the config work if you don't change the port number? That would indicate an issue with the VM to Host network.

**Comment by AlexanderShniperson** [comment] 2015-01-24 17:31
config works, but partially, i can connect to 22 port but certificate does not work.

**Comment by crawford** [comment] 2015-01-24 19:12
It sounds like you have an issue with your SSH keys. Make sure that your keys are present in `~/.ssh/authorized_keys` and try running your SSH client in verbose mode. That should give us a hint.

**Comment by pwaller** [comment] 2015-01-24 19:13
I hit a problem that sounds a bit like this on AWS. If I make a machine which doesn't have a public IP address, then I cannot SSH to it. The connection is accepted and I can see the fingerprint of the server, but it rejects my SSH key. I wasn't able to get to the bottom of it.

**Comment by AlexanderShniperson** [comment] 2015-01-24 19:31
can give you feedback monday, because i experimenting at my work pc.

**Comment by AlexanderShniperson** [comment] 2015-01-26 05:43
hmm, today it was able to connect via ssh key, below is verbose logs
i generated new etcd key and ssh key
```
Mac-mini-Aleksandr:YaDisk camkadev$ ssh -p 2211 -A -v -i /Volumes/hd2/YaDisk/coreos01_rsa core@10.255.100.167
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 102: Applying options for *
debug1: Connecting to 10.255.100.167 [10.255.100.167] port 2211.
debug1: Connection established.
debug1: identity file /Volumes/hd2/YaDisk/coreos01_rsa type 1
debug1: identity file /Volumes/hd2/YaDisk/coreos01_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6
debug1: match: OpenSSH_6.6 pat OpenSSH*
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<1024<8192) sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: RSA ab:61:60:c4:61:2c:f5:81:e0:44:f6:84:65:86:2b:ca
debug1: checking without port identifier
The authenticity of host '[10.255.100.167]:2211 ([10.255.100.167]:2211)' can't be established.
RSA key fingerprint is ab:61:60:c4:61:2c:f5:81:e0:44:f6:84:65:86:2b:ca.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[10.255.100.167]:2211' (RSA) to the list of known hosts.
debug1: ssh_rsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering DSA public key: /Users/camkadev/k24-sag-0-30
debug1: Authentications that can continue: publickey
debug1: Offering RSA public key: /Volumes/hd2/YaDisk/coreos01_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: key_parse_private_pem: PEM_read_PrivateKey failed
debug1: read PEM private key done: type <unknown>
Saving password to keychain failed
debug1: read PEM private key done: type RSA
Identity added: /Volumes/hd2/YaDisk/coreos01_rsa (/Volumes/hd2/YaDisk/coreos01_rsa)
debug1: read PEM private key done: type RSA
debug1: Authentication succeeded (publickey).
Authenticated to 10.255.100.167 ([10.255.100.167]:2211).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: Requesting authentication agent forwarding.
debug1: Sending environment.
debug1: Sending env LANG = ru_RU.UTF-8
Last login: Mon Jan 26 05:36:11 2015
CoreOS beta (557.0.0)
core@coreos01 ~ $ 
```

**Comment by crawford** [comment] 2015-01-26 17:58
It looks like it works now. Are you sure you didn't do anything differently this time around (other than the verbose flag)?

**Comment by AlexanderShniperson** [comment] 2015-01-26 18:01
i am 	generated new etcd key and ssh key

**Comment by crawford** [comment] 2015-01-26 18:05
The etcd discovery token shouldn't have any effect on SSH keys. I'm guessing there was a mistake with your previous setup. I'm going to close this for now, but please let me know if you run into this again.

**Closed by crawford** 2015-01-26 18:05 UTC

**Comment by gdgellatly** [comment] 2015-09-23 23:34
Just an FYI, sorry to revive old thread but first entry in google.  After struggling for a while with this the solution was to read the docs.  All YAML values in quotation marks and it started working.  I tink the problem is that if entries before need to be escaped / quoted then the key never loads, so changing the setting of the token could well have an effect.
